### ISSUE TITLE
Python throws 'TypeError' when starting kraken

### ISSUE THREAD

**Issue by denkfix** [mittagessen/kraken#10]
Using the latest _nidaba[kraken]_ release, I end up with a TypeError when starting kraken. Most likely a misconfiguration problem. I ran through the procedure at http://openphilology.github.io/nidaba/index.html and I am on Ubuntu 14.04

Any hints are greatly appreciated. Many thanks!

Traceback:
~/built/nidaba$ kraken

Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 7, in <module>
    from kraken.kraken import cli
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 25, in <module>
    from kraken.lib import models
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 29, in <module>
    from kraken.lib import pyrnn_pb2
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/pyrnn_pb2.py", line 20, in <module>
    serialized_pb=b'\n\x11proto/pyrnn.proto\x12\x06kraken\"\'\n\x05\x61rray\x12\x0b\n\x03\x64im\x18\x01 \x03(\r\x12\x11\n\x05value\x18\x02 \x03(\x02\x42\x02\x10\x01\"\xca\x01\n\x04lstm\x12\x1a\n\x03wgi\x18\x01 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wgf\x18\x02 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wgo\x18\x03 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wci\x18\x04 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wip\x18\x05 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wfp\x18\x06 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wop\x18\x07 \x02(\x0b\x32\r.kraken.array\"$\n\x07softmax\x12\x19\n\x02w2\x18\x01 \x02(\x0b\x32\r.kraken.array\"\xb1\x01\n\x05pyrnn\x12\x0c\n\x04kind\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ninput\x18\n \x02(\r\x12\x0f\n\x07noutput\x18\x0b \x02(\r\x12\r\n\x05\x63odec\x18\x0c \x03(\t\x12\x1c\n\x06\x66wdnet\x18\r \x02(\x0b\x32\x0c.kraken.lstm\x12\x1c\n\x06revnet\x18\x0e \x02(\x0b\x32\x0c.kraken.lstm\x12 \n\x07softmax\x18\x0f \x02(\x0b\x32\x0f.kraken.softmax'
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by mittagessen** [comment]
It seems to be caused by the protobuf (not clstm) created class which does not expect the syntax field. Could you show the output of ``pip show protobuf``? Kraken requires a beta release of the protobuf libraries to be python2 and python3 compatible but the correct version should be installed automatically by pip.

**Comment by denkfix** [comment]
Well, okay:
Name: protobuf
Version: 3.0.0-alpha-1
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools

**Comment by mittagessen** [comment]
Hmm that's interesting. Is there a syntax field described in the man page of ``pydoc google.protobuf.descriptor``? It looks like a mismatch of protobuf versions from here.

In what kind of environment are you running nidaba/kraken? Distribution, virtualenv, etc.

**Comment by denydias** [comment]
Hi @mittagessen,

I'm trying your code and I faced this very same issue as soon as kraken is installed, no matter if it happens through `pip install kraken` or `git clone;cd;pip install .`.

Here are some system info:

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"

$ pip list|grep -e "kraken\|protobuf\|click\|future\|dominate\|regex\|numpy"
click (6.2)
dominate (2.1.16)
future (0.15.2)
kraken (0.7.4)
numpy (1.8.2)
protobuf (3.0.0-alpha-1)
regex (2015.11.22)
```

I 've tried to remove `protobuf` to try an older release with:

```
$ sudo pip uninstall protobuf
$ sudo pip pip install protobuf==2.6.1
```

Still no luck. Then I've tried with 3.0.0a2.

```
$ sudo pip uninstall protobuf
$ pip install protobuf==3.0.0a2
```

Then:

```
$ kraken --help
Usage: kraken [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...

Options:
  -i, --input <PATH PATH>...
  -c, --concurrency INTEGER
  -v, --verbose
  --help                      Show this message and exit.

Commands:
  binarize
  get
  list
  ocr
  segment
  show
```

So, I leave the info for the newcomers. Maybe you could try to update `requirements.txt` to read:

```
protobuf==3.0.0a2
```

**Comment by mittagessen** [comment]
it It already requires protobuf 3.0.0a3 which is the latest version on pypi and should override your version 3.0.0-alpha-1 (???) which isn't even on pypi. I suspect there is some version comparison fuck up in older pip  versions causing the already installed version of protobuf to compare higher than newer ones. I'll have a look at the pip source code later to find out where the error lies and find a workaround (probably just pinning the dependency completely).

**Comment by mittagessen** [comment]
As the commit message says pip failed to calculate the correct version to install, installing protobuf-3.0.0-alpha-1 instead of protobuf>=3.0.0a2 which wouldn't be a problem if the protobuf maintainers would stick to one way to tag their alpha releases. Recent-ish pip versions will normalize 3.0.0-alpha-1 to 3.0.0a1 and prefer the newer alpha releases. Let's hope this does not crop up again when 3.0 becomes stable.

**Comment by denydias** [comment]
Hi, @mittagessen.

I've pinned protobuf at 3.0.0a2 as 3.0.0a3 is a no go in my environment (get the same `TypeError` as OP). kraken works fine with it.

Anyway, I see you have pinned it to 3.0.0a3. That's fine... hopefully, someone facing the same problem is going to find this issue.

For the records, Ubuntu 14.04 uses pip 1.5.4. This is very old compared to the current 7.1.2.

**Comment by mittagessen** [comment]
If you get the same error with 3.00a3 I'm more than willing to change the pin to 3.00a2. Weirdly enough I don't get the above error with 3.00a3. Is it exactly the same one or a different TypeError?

**Comment by denydias** [comment]
Yes, @mittagessen. The exact error is:

```
# kraken --help
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 7, in <module>
    from kraken.kraken import cli
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 25, in <module>
    from kraken.lib import models
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 29, in <module>
    from kraken.lib import pyrnn_pb2
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/pyrnn_pb2.py", line 20, in <module>
    serialized_pb=b'\n\x11proto/pyrnn.proto\x12\x06kraken\"\'\n\x05\x61rray\x12\x0b\n\x03\x64im\x18\x01 \x03(\r\x12\x11\n\x05value\x18\x02 \x03(\x02\x42\x02\x10\x01\"\xca\x01\n\x04lstm\x12\x1a\n\x03wgi\x18\x01 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wgf\x18\x02 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wgo\x18\x03 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wci\x18\x04 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wip\x18\x05 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wfp\x18\x06 \x02(\x0b\x32\r.kraken.array\x12\x1a\n\x03wop\x18\x07 \x02(\x0b\x32\r.kraken.array\"$\n\x07softmax\x12\x19\n\x02w2\x18\x01 \x02(\x0b\x32\r.kraken.array\"\xb1\x01\n\x05pyrnn\x12\x0c\n\x04kind\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06ninput\x18\n \x02(\r\x12\x0f\n\x07noutput\x18\x0b \x02(\r\x12\r\n\x05\x63odec\x18\x0c \x03(\t\x12\x1c\n\x06\x66wdnet\x18\r \x02(\x0b\x32\x0c.kraken.lstm\x12\x1c\n\x06revnet\x18\x0e \x02(\x0b\x32\x0c.kraken.lstm\x12 \n\x07softmax\x18\x0f \x02(\x0b\x32\x0f.kraken.softmax'
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

But now see how weird some things are. To get the same message again, I did a `pip uninstall protobuf`, then `pip install protobuf==3.0.0a3`. This time, `kraken --help` ran smooth.

To reproduce the message above, I hat to install protobuf 2.6.1.

One of the two:

1. pip 1.5.4 is deeply broken and I was deceived by it when installed the first time. I was expecting it to follow `requirements.txt`, but it end up resolving protobuf to 2.6.1 and I missed that in the output.

2. As I just removed protobuf and installed it from sratch (no pip cache in place) with all other kraken dependencies already in place, then maybe something happened different during protobuf's configuration and compile time - an available module or function that wasn't there by the time protobuf was installed for the first time. This is a poor guess due to the fact that protobuf is the last package to appear in `requirements.txt`, but who knows.

In any case, strange enough. Unfortunately I don't have a clean system to test neither. Will do when I got the chance to.

At least two equivalent system behaves the same, which is a very good news! ;]

**Comment by denydias** [comment]
By the way, I'm an uneducated person and forgot to thank you by kraken itself and your willing to help! ;]

Thank you very much for both, @mittagessen.

**Comment by mittagessen** [comment]
You're welcome.
