### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by akhlaghiandrew** [mittagessen/kraken#102]
This is my first time using Kraken with a virtual environment. I've installed conda, setup the virtual environment, and activated it. When I try to use Kraken commands i get the following error:

ImportError: No module named kraken.kraken

Thanks for all the work you're doing on Kraken.

**Comment by mittagessen** [comment]
This is weird. There is no module `kraken.kraken` and the shell shouldn't reference one. Are you using the python 2.x or python 3 version of anaconda? It shouldn't really matter because it does reference python 3.6 as a reference but that is the only thing I can imagine right now causing this error.

**Comment by mittagessen** [comment]
So you're using Mac OS X? Can you try changing the line:

```
  - python>=3.6
```

to

```
   - python==3.6
```

and try to reinitialize the environment? This is only a guess but it might allow pip to pull the wheel from pypi. I can try to find a Mac OS X machine sometime next week to do a bit of digging.

**Comment by akhlaghiandrew** [comment]
I am using mace. the change
`-python>=3.6` to `-python==3.6`
worked perfectly. i did the edit using nano in the command line.

**Comment by mittagessen** [comment]
Thanks, I'll change the environment file.
