### ISSUE TITLE
Command for grayscale image

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#117]
Hey @mittagessen ,
Still me. @Jean-baptiste-camps told me it is possible to run Kraken on color or gray scale image, thus avoiding binarization. Could you tell me more about this ?
Cheers,

**Comment by mittagessen** [comment]
It is a bit annoying because you have to supply the segmentation separately, i.e. the process for is:

`$ kraken -i $in $out binarize segment && kraken -i $in $txt_out ocr -l $out ...`

Of course you need models trained to support this. For grayscale nothing needs to be changed, just supply the image files. Color images require you to change the VGSL input definition of the model when training, i.e. change:

` [1,48,0,1 Cr3,3,32 Do0.1,2 Mp2,2 Cr3,3,64 Do0.1,2 Mp2,2 S1(1x12)1,3 Lbx100 Do]`

to:

` [1,48,0,3 Cr3,3,32 Do0.1,2 Mp2,2 Cr3,3,64 Do0.1,2 Mp2,2 S1(1x12)1,3 Lbx100 Do]`

telling it to expect 3 channel inputs.

**Comment by PonteIneptique** [comment]
Thanks for the answer ;) I'll see if that improves the results.

Although, one thing here was according to expectations : I did not expect that it could be segmented in grayscale (that's the error that I got).

**Comment by PonteIneptique** [comment]
Hey @mittagessen , commenting here since I finally got to try color mode. Running with `--spec '[1,48,0,3 Cr3,3,32 Do0.1,2 Mp2,2 Cr3,3,64 Do0.1,2 Mp2,2 S1(1x12)1,3 Lbx100 Do]'` raises the error `Error: Invalid mode RGB for line dewarping`
