### ISSUE TITLE
New training interface

### ISSUE THREAD

**Issue by QuLogic** [mittagessen/kraken#14]
I know this is already listed as a missing feature in the documentation. However, I am wondering what exactly the plans are going forward? What sort of interface, API, etc. is it going to have and/or are under consideration?

**Comment by mittagessen** [comment]
Sorry for the delay. As I do mostly work with humanities people a bundle like the transcription interface ocropus provides, i.e. something showing the text image and text box next to it, would be ideal. 
An extension to the original ocropus html bundle that I'd like to see is a system that shows the whole page image with lines as recognized by the page segmentation and the ability to edit the bounding boxes in the transcription system itself. After transcription the data could be saved and either processed by the transcriber  themselves or some third party. 

So the new training interface will consist of a transcription interface and the actual training process training on the line image-text pairs. As the training process only requires these pairs I'd consider the frontend to be the constricting factor, especially as I'm not a frontend developer so anything I'll cook up will probably be a horrible mess.

**Comment by wanghaisheng** [comment]
@mittagessen http://kraken.re/ketos.html lack of  documentation training from scratch

**Comment by mittagessen** [comment]
There is a (bug-riddled) transcription interface that can be accessed using ``ketos transcrib`` and ``ketos extract`` (see their help option for further info) but actual training is still through the clstmocrtrain command until the new python interface to clstm is hammered out. By and large there is no documentation because there is nothing that I'd like to document/people to use as is without lots of handholding.

**Comment by wanghaisheng** [comment]
@mittagessen  i see thx
