### ISSUE TITLE
kraken binarize produces a VisibleDeprecationWarning

### ISSUE THREAD

**Issue by lunactic** [mittagessen/kraken#18]
When I use

```kraken binarize```

I always receive the following warning:

```
/usr/lib/python2.7/site-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = empty(shape, dtype, order)
```

The binarized image is still computed. But I am trying to run the command unattended and raise an error if something is reported to the standard error output (which the warning unfortunately is).

Do you know of a way to disable the warning or where I would have to search in order to fix this?

**Comment by mittagessen** [comment]
As a side note (don't know your use case), the binarization (and everything else) has been encapsulated in functions so it may be easier to use it directly from python. Further the exit code should be non-zero on any error conditions, so you may want to take that into account.

**Comment by lunactic** [comment]
Thanks for the reply and the fix in #20.

For my usecase I want to expose the binarization method as a RESTFul WebService through my research project (called DIVAServices: https://diuf.unifr.ch/main/hisdoc/divaservices).

I have done this with ocropus already (can be tested through DIVAServices-Spotlight at http://divaservices.unifr.ch/spotlight).

If you want more details on how this work feel free to contact me.

**Comment by mittagessen** [comment]
Ah I talked with Prof. Liwicki at a workshop a few weeks ago a bit about it. 

The binarization of kraken and ocropus is identical for now as it seems to perform well enough for most use cases and benchmarking binarization is sketchy at best (I'm working my way backwards through the processing chain trying to improve stuff). If there's a foreign function interface for Javascript I'd recommend calling nlbin() directly otherwise invoking executables is probably fine although fraught with security issues if done incorrectly.

**Comment by amitdo** [comment]
Sauvola based binarization:
https://github.com/tmbdev/ocropy/blob/master/OLD/ocropus-sauvola
