### ISSUE TITLE
Ketos linegen produces unreadable content in text line images for Arabic

### ISSUE THREAD

**Issue by mohamed-ali** [mittagessen/kraken#223]
Thanks for your effort in developing and maintaining this library

I attempted to generate some data using an arabic text with the amiri font but the produced text line images aren't correct as you can see:

![image](https://user-images.githubusercontent.com/2883926/92311518-02e7fb80-efb8-11ea-90fc-3ad0bba4f3a2.png)

I installed kraken like this:

```bash
apt install libpangocairo-1.0 libxml2 libblas3 liblapack3 python3-dev python3-pip
pip install kraken
```

And I run the linegen command as follows:

```
!ketos linegen --strip -ur NFC -u NFD -l ara -f Amiri-0.113/Amiri-Regular.ttf  -o trainingdata/ dataset/arabic.txt
```

You can also find a minimal reproducible example in this colab notebook: https://colab.research.google.com/drive/1tESMIwjk14Cc3XB4QkjgwhLSVSP7IJBH?usp=sharing

Could you point me to how I can fix this issue? Thanks.

**Comment by mittagessen** [comment]
* Mohamed Ali Jamaoui :: 2020-09-05 20:45 Sat:
> Thanks for your effort in developing and maintaining this library
> 
> I attempted to generate some data using an arabic text with the amiri font but the produced text line images aren't correct as you can see:
> 
> ![image](https://user-images.githubusercontent.com/2883926/92311518-02e7fb80-efb8-11ea-90fc-3ad0bba4f3a2.png)
> 
> I installed kraken like this:
> 
> ```bash
> apt install libpangocairo-1.0 libxml2 libblas3 liblapack3 python3-dev python3-pip
> pip install kraken
> ```
> 
> And I run the linegen command as follows:
> 
> ```
> !ketos linegen --strip -ur NFC -u NFD -l ara -f Amiri-0.113/Amiri-Regular.ttf  -o trainingdata/ dataset/arabic.txt
> ```

The font has to be installed in the fontconfig system. Usually it is
sufficient to put the ttf file in .fonts and run `fc-cache` but I've got
no idea how/if the typeface system in colab is configured. Just pointing
at a ttf file doesn't work fork as pango always runs through
fontconfig's resolution process that handles substitution and so on. In
fact, because the typeface doesn't get get auto-substituted and you just
get garbage makes me suspect that fontconfig isn't configured at all.

Maybe try installing the font through apt? It is in the debian
repositories as `fonts-hosny-amiri`.

**Comment by mohamed-ali** [comment]
Thanks for the clarification. 

Adding this command after unzipping the font is sufficient to solve the problem:

```
!mv Amiri-0.113 /usr/share/fonts/truetype/Amiri
```

Then, the line generation should be called as follows:

```
!ketos linegen --strip -ur NFC -u NFD -l ara -f Amiri  -o trainingdata/ dataset/arabic.txt
```
