### ISSUE TITLE
one character recognition

### ISSUE THREAD

**Issue by josef821** [mittagessen/kraken#238]
i try to convert this image but it not working in one character.
![shot](https://user-images.githubusercontent.com/9824705/106187492-f52b5080-61ba-11eb-9f72-60a0f8a823f1.png)
how can i convert images like this?
----
and i have another question.
how train with grandtrurh ( image and line.txt ) working? ( just for my interest )
i want to know how lstm works to recognize character? how it pair character with text and then learn that?
for Arabic language character is join together.how it works? can you explain that simply? thank you very much.

**Comment by mittagessen** [comment]
The default networks are trained on full document pages and sequences respectively and are probably not able to find the 'line' and/or classify single characters like that. In addition, if the images are very small horizontally it is possible that the subsampling in the recognition network (dilated convolutions and maxpooling) cause the image to be 'swallowed' completely making recognition of image smaller than 48x8 impossible.

Training with the old (non-trainable) segmenter is documented [here](http://kraken.re/ketos.html).

The network is trained with a loss function called CTC. Instead of separating the line into character regions (framewise training) and telling the net to output a particular character label at a certain position, it just maximizes to cumulative probability of all paths through the output matrix that produce the correct character sequence. The network can thus 'place' the characters wherever it wants and there is no need to segment connected scripts like Arabic or Syriac. While that means in principle that character locations in the network output are not correlated to their actual location in the line, text recognition networks are sufficiently crappy at long-term modelling that they are fairly close in practice.

**Comment by josef821** [comment]
hi. i still have problem in this case :(
in tesseract can set PSM ( Page Segmentation Mode ) to recognize one character.
can you help me to solve this problem in kraken? one character recognition will be useful in tables cell recognition.
