### ISSUE TITLE
issue with pages without text

### ISSUE THREAD

**Issue by pverkind** [mittagessen/kraken#247]
Hi, I ran into a problem trying to OCR pdf files that contain empty pages (kraken version: 3.0.0.0b21.dev6). 
I extracted the images in png format from the pdf using the poppler utility pdftoppm - this creates one image per page.

When I run kraken on the page images that contain text, it works without problem. 

```
kraken -i <img_fp> <dest_fp> binarize segment -d horizontal-rl -p 20 20 ocr -m <pth_to_model> --pagexml
```

However, for pages that don't contain any text, kraken gets stuck in the segmentation step: 

![image](https://user-images.githubusercontent.com/16897431/118972621-07e7b200-b971-11eb-8f14-37562a44818a.png)

I have created a crude workaround for this in my Python script, but I thought I should flag this issue here...

(I have attached such a png file of an empty page)

![0677IbnMuyassar AkhbarMisr_007](https://user-images.githubusercontent.com/16897431/118971370-a07d3280-b96f-11eb-836a-530737c1ae61.png)

**Comment by mittagessen** [comment]
* pverkind :: 2021-05-20 13:54 Thu:
> Hi, I ran into a problem trying to OCR pdf files that contain empty pages (kraken version: 3.0.0.0b21.dev6). 
> I extracted the images in png format from the pdf using the poppler utility pdftoppm - this creates one image per page.
> 
> When I run kraken on the page images that contain text, it works without problem. 
> 
> ```
> kraken -i <img_fp> <dest_fp> binarize segment -d horizontal-rl -p 20 20 ocr -m <pth_to_model> --pagexml
> ```
> 
> However, for pages that don't contain any text, kraken gets stuck in the segmentation step: 
> 
> ![image](https://user-images.githubusercontent.com/16897431/118972621-07e7b200-b971-11eb-8f14-37562a44818a.png)

The segmenter should just skip empty pages but yours aren't really empty
as they contain non-0/255 pixels, probably because they were dumped as
jpegs in the pdf. In fact, on the sample page you attached it is just
fairly slow because it find ~8k lines in there. The new trainable
segmenter (-bl option) doesn't have this problem but requires
transcription models trained for it.

BTW: You can just feed PDFs directly into kraken now. No need to split
into separate image files:

```
kraken -f pdf -I xyz.pdf ....
```
