### ISSUE TITLE
Error with -a argument

### ISSUE THREAD

**Issue by Heresta** [mittagessen/kraken#251]
Hi, 

I have a segmentation model and a HTR model.  

I would like to have an ALTO xml output after their use. But it seems that I can't use an -a argument : it raises an error despite of the documentation online.

There is a screenshot of the error : 
![Capture d’écran de 2021-06-02 16-45-25](https://user-images.githubusercontent.com/74970052/120502695-eea82200-c3c2-11eb-8d99-b7d81fb7c6b3.png)

When I check `kraken segment --help`, -a argument doesn't appear.
![Capture d’écran de 2021-06-02 16-55-47](https://user-images.githubusercontent.com/74970052/120503250-6c6c2d80-c3c3-11eb-969e-6a31e3c3c137.png)

This same error has been also encountered by other users.  But on there side, when they check `kraken segment --help`, -a argument does appear.
![Capture_decran_de_2021-06-02_14-36-18](https://user-images.githubusercontent.com/74970052/120503022-3a5acb80-c3c3-11eb-9757-70fb50fe3622.png)

png used can be found on GitHub (available [here](https://github.com/Heresta/datasetsOCRSegmenter17/blob/main/Data/Balzac1624_Lettres_btv1b86262420_corrected/png/Balzac1624_Lettres_btv1b86262420_corrected_0062.png)).
Segment model used can be found on GitHub (available [here](https://github.com/Heresta/datasetsOCRSegmenter17/blob/main/Model/Segment/segment17.mlmodel))

Ubuntu v. 18.04.5
My Kraken v. 3.0.0.0b26.dev1 / Other Kraken v. 3.0.0.0b25.dev6
Modes of installation : I tested with pip, conda and git clone, they all return the same issue.

Thanks in advance for your help

**Comment by mittagessen** [comment]
The documentation on the web site is for the last stable version of kraken. Up-to-date docs for the beta are in the [docs](https://github.com/mittagessen/kraken/tree/master/docs) directory.

The output format switches have been moved from the `ocr` subcommand to the overall `kraken` arguments as they can now serialize the results of intermediate processing steps into XML directly as well. So instead of running:

```
$ kraken -i a.png o.txt ... ocr -m x.mlmodel -a
```

you'd run:

```
$ kraken -i a.png o.txt -a .... ocr -m x.mlmodel
```

Hope that clears it up.
