### ISSUE TITLE
How to test `ketos segtrain` model 

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#263]
Disclaimer: I have not tested it because I am currently running something already on the GPU.

When I look at `ketos test`, it seems capable to load segmentation model. However, the same script seems to need characters for scoring. I expect then `ketos test` to not be able to test the segmentation. Do you have any script laying out for this purpose ?

Happy to have feedback on #262  for the best metric to chose as well :)

**Comment by mittagessen** [comment]
There's not a good way to test. For publication you can take the raw segmentation output, convert lines to a format the cbad evaluation tool uses, compute those, and compute the region IoU scores separately. Gives you nice numbers to put in an article but the cbad metric has some issues like the lack of consideration of line orientation.

For visual validation, there is the `segmentation_overlay.py` script in contrib/.

The problem is really that you want to validate 4 (5/6) different things: baseline detection, baseline classification, baseline orientation, and regions + appropriateness of baselines for polygonisation and subsequently recognition.
