### ISSUE TITLE
Installation requirements on Debian 8.6 (Jessie)

### ISSUE THREAD

**Issue by wollmers** [mittagessen/kraken#31]
Following the installation instruction in the documentation didn't work on Debian 8.6 (Jessie).

What I had to do:

```
apt-get install build-essential
apt-get install git

apt-get install libpangocairo-1.0 libxml2 libblas3 liblapack3

apt-get install libxml2-dev
apt-get install libxslt1-dev
apt-get install python-scipy
apt-get install python-pip

pip install lxml
pip install jinja2
pip install regex
pip install python-bidi
pip install numpy
pip install kraken
```

**Comment by mittagessen** [comment]
The issue is that the pip shipped with Debian stable is extremely old (1.5.x) and doesn't install numpy correctly in one pass and compiles a lot of stuff that is available as binary wheels on pypi, therefore requiring headers for some libraries. The "best" solution for python software in general is [virtualenv](https://pypi.python.org/pypi/virtualenv) to keep everything nicely separated.

In fact it was documented your way (except installing scipy from the repositories) until a few days ago:
```
$ apt-get install libpangocairo-1.0 libxml2 libblas3 liblapack3 libblas-dev liblapack-dev libxml2-dev
$ pip install numpy
$ pip install kraken
```

**Comment by QuLogic** [comment]
Jessie appears to include numpy 1.8.2; why does it need to be installed via `pip` in the first place?

**Comment by mittagessen** [comment]
It doesn't really. It's just that python packaging (or rather APIs are extremely unstable) is so completely broken that it's best to install everything in virtualenvs and then you obviously need to install numpy from pypi. kraken's dependencies are some of the better written libraries and reasonably stable but installing something else globally will still sooner or later break your system (looking at you protobuf).

**Comment by wollmers** [comment]
@mittagessen I can imagine that virtualenv compares to perlbrew (Perl 5), rakudobrew (Perl6) or homebrew (Mac OS X). But I am not experienced as a Python developer and will not be this year (maybe 2017;-).

The intention of submitting this this issue was to document the installation problems in real life on a nearly fresh installed machine.
