### ISSUE TITLE
Training RecognitionModel and SegmentationModel - which Version 

### ISSUE THREAD

**Issue by nPlattner** [mittagessen/kraken#330]
Hello, I didn't find any errors or anything like that, I just have one question: I'm currently trying to train models. Both RecognitionModel and SegmentationModel.
I can't get the code snippets from https://kraken.re/master/api.html to work with the currently released version (3.0.6 if I'm not mistaken). When comparing the train.py between 3.0.6 and master, I noticed that there are some changes in this area. Are the conversions regarding model training complete and will the new version be released soon? Or is it better to stick with the 3.0.6 code snippets? Are the conversions already stable enough to rely on?

**Comment by mittagessen** [comment]
If you're looking at the documentation for the master branch you should try to run the code with master branch kraken installed. There latest stable release is 4.0 (the current master branch docs work for that release) but I forgot the redact a github release as that isn't automatically done. There packages on pypi are for 4.0 though the anaconda one didn't run through because conda crapped out halfway through the build.
