### ISSUE TITLE
Conda hang during install from master

### ISSUE THREAD

**Issue by colibrisson** [mittagessen/kraken#346]
When installing Kraken directly from the repo using `conda env create -f environment.yml`, conda hang during environment solving.  I waited a couple hours but I didn't get any error message. 

I'm using a fresh conda 4.10.3 on Ubuntu 21.10.

The error also occur when installing from environment_cuda.yml.

**Comment by dstoekl** [comment]
I installed yesterday night _cuda  with no problem.

**Comment by colibrisson** [comment]
@dstoekl which conda version do you use ?

**Comment by mittagessen** [comment]
It doesn't hang, conda is just exceptionally slow recently when resolving dependencies. You can either install the binary conda packages or use [mamba](https://github.com/mamba-org/mamba) which is infinitely faster to create the environment. 

Unfortunately, it is a bit of a pickle. We can speed up the process by just pinning every dependency on a specific version (we already do for the binary packages as otherwise the CI would time out) but that can break other things on certain platforms or when using kraken in conjunction with other packages.
