### ISSUE TITLE
Image orientation is detected incorrectly

### ISSUE THREAD

**Issue by lauxley** [mittagessen/kraken#394]
Bug was reported on escriptorium repository here: https://gitlab.com/scripta/escriptorium/-/issues/705  
And was reproduced in kraken 4.1.2 and 4.2

**Comment by mittagessen** [comment]
The problem is that their viewer auto-rotates that image for display based on the EXIF orientation field (it is set to 6/right-top) and kraken processes the image in the orientation it is saved in. As it is just a metadata field that is also frequently mis-set I'd suggest them to rotate the images based on the EXIF value manually or maybe add a feature like that into escriptorium.
