### ISSUE TITLE
Windows 

### ISSUE THREAD

**Issue by MedoHamdani** [mittagessen/kraken#411]
Is there any possibility to run it in Windows?
Can Ubuntu be installed from Windows Store and then be used?

Does this model "Kraken:arabPersPrBigMixed_best(1)" ring a bell? If yes, from where to download it?
More details in this [video ](https://www.youtube.com/watch?v=N0hSNC3YvD4) in minute 05:21 in the Open ITI project

Thanks,

Medo Hamdani

**Comment by mittagessen** [comment]
Sorry, I was on vacation and my response fell off the mountain of post-vacation catch-up work. It isn't officially supported as we don't have many Windows machines laying around with which to test kraken regularly. But someone just ran everything on Ubuntu/WSL (even CUDA seems to work) but you need to use the pip install.

I don't have this model laying around but you can just send them an email and ask. They probably haven't published it in the model repository because they still want to improve it, I guess.
