### ISSUE TITLE
Provide half-precision at prediction time

### ISSUE THREAD

**Issue by PonteIneptique** [mittagessen/kraken#459]
I am benchmarking half precision on segmentation, the results are incredible in terms of memory usage.

Note: CUDA (Nvidia-smi report) is a bit heavier (overhead of ~ 1000 MiB, which would maybe advocate for batch segm prediction ?)
Without autocast: 2136MiB
With autocast: 1372MiB

Results with the default BLLA model.

PR incoming.

Benchmarking code:

```
import torch
from PIL import Image
from kraken import blla
from kraken.lib.vgsl import TorchVGSLModel

INPUT: str = "page_16.jpg"
im = Image.open(INPUT)
mask = None
SEGMENTATION_DEFAULT_MODEL = './kraken/blla.mlmodel'
torch.cuda.empty_cache()
model = TorchVGSLModel.load_model(SEGMENTATION_DEFAULT_MODEL)
model.to("cuda:0")
res = blla.segment(
    im, 'horizontal-lr', mask=mask, model=model, device="cuda:0", raise_on_error=True,
    autocast=False
)

print(f"{torch.cuda.max_memory_reserved()//1024//1024}MiB")
```

Data = 
![page_16](https://user-images.githubusercontent.com/1929830/221514973-5f99853e-886a-476d-a4b3-13864a57583e.jpg)

**Comment by PonteIneptique** [comment]
FYI: NVIDIA-SMI reports: 2800 vs 3500

**Comment by colibrisson** [comment]
You do inference on GPU? As Ben often says, during segmentation most of the time is spent in post-processing on the CPU. I my experience, it is faster to use a process pool and perform multiple inferences in parallel on the CPU.

**Comment by colibrisson** [comment]
I would really like to see if the new [toch.compile](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html) can speed up inference, both CPU and GPU.

**Comment by PonteIneptique** [comment]
> You do inference on GPU? 
Yup, I do

> As Ben often says, during segmentation most of the time is spent in post-processing on the CPU. I my experience, it is faster to use a process pool and perform multiple inferences in parallel on the CPU.

I assume it depends on your CPU though ? Are we talking mainline CPUs or Workstation/Serveurs CPU ?

**Comment by PonteIneptique** [comment]
Adding on:

> As Ben often says, during segmentation most of the time is spent in post-processing on the CPU. I my experience, it is faster to use a process pool and perform multiple inferences in parallel on the CPU.

Then wouldn't it make sense to move to batched prediction to make the compute faster and the serialization parallelized ?

**Comment by colibrisson** [comment]
> Then wouldn't it make sense to move to batched prediction to make the compute faster and the serialization parallelized ?

That's a good point. By the way, on Intel CPU I found that the [Intel Extension for Scikit-learn](https://intel.github.io/scikit-learn-intelex/) can help speed the post processing.

**Comment by PonteIneptique** [comment]
Autocast on recognizer seems to have 0 impact or too small to worry about it.

**Comment by PonteIneptique** [comment]
I assume it could have an impact if OCR inference were batched as well, but this is only a thought

**Comment by mittagessen** [comment]
> FYI: NVIDIA-SMI reports: 2800 vs 3500

On which GPU architecture? I ran a quick test last week on our Turing GPUs and there the memory usage actually increased slightly.

> I would really like to see if the new [toch.compile](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html) can speed up inference, both CPU and GPU.

The new torch compile can't speed up anything because it doesn't even compile our current nets without crashing. I tried last week. The dynamic shape shape code seems to be fairly unusable right now.

>  That's a good point. By the way, on Intel CPU I found that the [Intel Extension for Scikit-learn](https://intel.github.io/scikit-learn-intelex/) can help speedup the post-processing.

The heavy stuff is in scikit-image for which there are no separate speedup extensions.

> Then wouldn't it make sense to move to batched prediction to make the compute faster and the serialization parallelized ?

Multiprocessing is ugly and hiding multiprocessing inside library calls is even uglier. Spawning off random processes is a recipe for disaster, especially as pytorch has it's own implementation of the multiprocessing module that's doing whatever it is doing and kraken is used as part of eScriptorium which uses celery which *also* has its own multiprocessing module. We already need to circumvent celery's fork-in-children prevention because of that.

> I assume it could have an impact if OCR inference were batched as well, but this is only a thought

The `TorchSeqRecognizer` already supports batch prediction but all the code in `rpred.rpred` doesn't. Because of the slow line extraction even running on GPU in the first place usually isn't worth it even with very fast CPUs and I/O. `extract_polygons` is 50%+ of recognition run time so reimplementing that would have an impact.

**Comment by PonteIneptique** [comment]
> On which GPU architecture? I ran a quick test last week on our Turing GPUs and there the memory usage actually increased slightly.

RTX 3090 Driver Version: 510.108.03   CUDA Version: 11.6

> Multiprocessing is ugly and hiding multiprocessing inside library calls is even uglier. Spawning off random processes is a recipe for disaster, especially as pytorch has it's own implementation of the multiprocessing module that's doing whatever it is doing and kraken is used as part of eScriptorium which uses celery which also has its own multiprocessing module. We already need to circumvent celery's fork-in-children prevention because of that.

I get this, but I would believe (I could be wrong though) that profiting from GPU compute and, "at worst", post-processing on cpu sequentially might yield benefits ? Again, I am fine with the current state, I would not worry about it. I am already happy that we can have `--autocast` on prediction :D
