### ISSUE TITLE
WARNING  Invalid line 37 in  arrow_dataset.py:57

### ISSUE THREAD

**Issue by particitae** [mittagessen/kraken#496]
![FRAN_0393_00878_L](https://user-images.githubusercontent.com/37141614/233291932-03d08eff-d2bf-41d9-ba95-521c197be9b7.jpg)

I got a lot of warnings "WARNING  Invalid line 37 in              arrow_dataset.py:57", by example, with this picture.
Any ideas ?

source : 
https://zenodo.org/record/7575693

**Comment by mittagessen** [comment]
I don't know why but there seem to be quite a few lines in the dataset that got bounding polygons that extend beyond the image. That shouldn't really happen, especially as the data comes from eScriptorium which uses kraken's polygonizer which in turn clips any bounding polygons to the image. If you don't absolutely need those lines for training I'd suggest ignoring it, otherwise I can add some  clipping code to the polygon extractor side of the pipeline.

**Comment by particitae** [comment]
thanks for your reply
