### ISSUE TITLE
How to optimize the GPU use in a transcription process ?

### ISSUE THREAD

**Issue by particitae** [mittagessen/kraken#517]
When in my script, i connect the segmentation step and the recognition step with the GPU processor, the GPU processor is seldom sollicited contrary to the CPU. I can even watch that the CPU slows down the entire process. 
example : seg_model.set_num_threads(1)
seg_model.to(device='cuda')
models.load_any("Model.mlmodel", device='cuda')

Is it possible to optimize the relation between the GPU and the CPU ? any tips ?

**Comment by colibrisson** [comment]
Usually, you disable multi-threading (`set_num_threads(1)`) when you have many processes making inferences in parallel on the CPU. If you are using a GPU, disabling multi-threading will considerably slow down inference.

**Comment by PonteIneptique** [comment]
IMHO, if we alread had the discussion with @mittagessen in [regarding speed-up of prediction](https://github.com/mittagessen/kraken/issues/459#issuecomment-1446066240).

Basically, the line extraction process is slow, which means in return that there is no perfect combination that could really make use of GPU power. I think I got the best inference speed (Nvidia 3090) by running segmentation on GPU (because "huge math") and recognition on CPU (because of a lot of "small maths").

I did not benchmark specifically but that was definitely my feeling. As long as we don't have batched GPU recognition, I think it's better to CPUize the recognition. But I can be corrected :)

**Comment by colibrisson** [comment]
It's a lot faster to run multiple inference processes in parallel on the CPU using `multiprocessing`, for segmentation as well as recognition.

**Comment by PonteIneptique** [comment]
If you're coding the thing in python, definitely might be :)

If you're using shell, `parallel` works well with segmentation in half precision for segmentation + gpu and recognition on CPU was a sweet spot on my machine (or at least seemed so)
