### ISSUE TITLE
Website Redirect

### ISSUE THREAD

**Issue by waynegraham** [mittagessen/kraken#533]
The web page (<https://kraken.re/>) returns a 404 error after the redirect to <https://kraken.re/main/index.html>. [Build 207](https://github.com/mittagessen/kraken/actions/runs/5604715129) shows a successful pages build, and running `sphinx-multiversion docs build/html` locally builds the docs as expected. 

I did note that the tags all work as expected (e.g. <https://kraken.re/4.3.0/index.html>) and navigation works as expected, but it appears the directory for `main` isn't built on gh-pages for some reason in the deployment workflow.

**Comment by stweil** [comment]
I can confirm that https://kraken.re/ is still failing. Ping @mittagessen.

**Comment by mittagessen** [comment]
it's a long-standing bug in the gh-page publication action. When a new release is tagged it pushes the sphinx docs for the release but because the last commit is a tag and not just the main branch no docs for the default case are created. I thought I had fixed it before August with a dummy commit but there was an error in the run.

**Comment by mittagessen** [comment]
Well, for some reason the sphinx tasks succeeds now and the website works again. No idea why though and I couldn't find the source of the original error even after spending way too much time on tracking it down.
