### ISSUE TITLE
Issues in using kraken

### ISSUE THREAD

**Issue by aayn** [mittagessen/kraken#54]
Hi,

I'm facing several issues while running `kraken`. I'm running Ubuntu 16.04 with `python 2.7.12`.
One of them is, after succesful binarizing, `segment` throws a segmentation fault.
```
root@de2e05f9d21b:~/integrated-ocr/images# kraken -i test_image1.jpg image.jpg binarize
Binarizing      ✓
root@de2e05f9d21b:~/integrated-ocr/images# kraken -i image.jpg lines.txt segment
Segmenting      Segmentation fault (core dumped)
```

The other issue I face is this:
```
root@de2e05f9d21b:~/integrated-ocr/images# kraken -i test_image1.jpg image.txt binarize segment ocr
Usage: kraken ocr [OPTIONS]

Error: Invalid value for "-m" / "--model": Mappings must be in format script:model
```

Any clues as to why this is happening? Let me know. I'm even ready to help you in fixing it (if these issues are indeed reproducible).

**Comment by mittagessen** [comment]
I assume you're using the master branch because both errors are related to the script detection feature. The first is from a wrong clstm version, they changed the semantics of some fields. Try using the separate_derivs branch of clstm. Could you tell me which commit you where building from?

The second one is a regression and correct in the latest commit.

**Comment by aayn** [comment]
Spot on. Both issues are now fixed. Thanks :)
