### ISSUE TITLE
[Suggestion] linegen - Use PangoCoverage

### ISSUE THREAD

**Issue by amitdo** [mittagessen/kraken#55]
https://developer.gnome.org/pango/stable/pango-Coverage-Maps.html

Tesseract's `text2image` tool use it. You might want to use it in `linegen.py`.

Search for 'coverage' in these files:
https://github.com/tesseract-ocr/tesseract/blob/master/training/text2image.cpp
https://github.com/tesseract-ocr/tesseract/blob/master/training/pango_font_info.h
https://github.com/tesseract-ocr/tesseract/blob/master/training/pango_font_info.cpp
https://github.com/tesseract-ocr/tesseract/blob/master/training/stringrenderer.h
https://github.com/tesseract-ocr/tesseract/blob/master/training/stringrenderer.cpp

**Comment by mittagessen** [comment]
That looks interesting, indeed although I doesn't seem to catch misrendering between different normalization forms because it's operating on a code point level. I'll add it when I get around to it.

**Comment by amitdo** [comment]
Apart from font coverage it uses other ways to check if the string can be rendered with a given font.
https://github.com/tesseract-ocr/tesseract/blob/master/training/pango_font_info.cpp#L343

**Comment by mittagessen** [comment]
I've seen that it also checkes for substitution glyphs but that particular error case can't be checked through Pango as it is an Harfbuzz issue that nobody knows how to fix nicely.

**Comment by christophered** [comment]
@theraysmith what do you think about mittagessen's observations?

**Comment by theraysmith** [comment]
Please explain exactly what you mean by "misrendering between different normalization forms"
Depending on exactly what that means, I think it is probably true that the current rendering system doesn't catch such problems, and I would be glad of help to fix it.

The current approach is to qualify fonts by test rendering the training text, then counting the fraction of characters that generated a bounding box output. This is very coarse, and probably results in some incorrectly rendered training data. The important thing is that it catches fonts that can't render the training text at all, despite claiming to support the language. (Eg a font may claim to support Serbian, but can only render Latin Serbian, and not Cyrillic Serbian.)

That said, incorrectly rendered training data *may not* harm the learning process much, as it may just learn an "alternative" way of rendering text, like 'a' vs _'a'_

**Comment by theraysmith** [comment]
OK that italic 'a' was supposed to be in a font that prints it in the other shape.

**Comment by mittagessen** [comment]
The issue occurs for example with polytonic Greek when trying to render grapheme clusters with diacritics in NFD using the Greek Font Society fonts which only contain glyphs for grapheme clusters in NFC. The code will catch that a substitution happened/coverage is not exact while the font itself is able to render the text correctly, just in another normalization form (or no defined normalization form at all). 

The underlying reason is the mapping between code points and glyphs, while it should be a mapping between grapheme clusters and glyphs. Unfortunately, there is no "easy" way to solve this and some specialized communities with quality requirements have a intra-community standard on how texts are normalized to ensure proper display.

**Comment by amitdo** [comment]
I guess one should 'query' the font file itself for coverage information.

Is there a tool that gets a text file and output a chars/glyphs coverage report?
