### ISSUE TITLE
Upgrade to shapely 2.0

### ISSUE THREAD

**Issue by La0** [mittagessen/kraken#601]
We (Teklia) are upgrading our Kraken worker to it inside [Arkindex](https://doc.arkindex.org/).

Our [base worker library depends on recent shapely 2.0.3](https://gitlab.teklia.com/workers/base-worker/-/blob/master/pyproject.toml?ref_type=heads#L15)

Do you have any blocker to stay on shapely 1.8.5 (released in october 2022) ?

**Comment by mittagessen** [comment]
Yes, there are numerical differences between 1.8.4 and 2.x that break polygon calculation in some cases. See [here](https://github.com/mittagessen/kraken/issues/430) for more details.

It's on the radar but low priority. Frankly, anytime we bump up shapely versions we're finding undocumented behavior changes in corner cases for months afterwards. I'd like to avoid that if possible because it's a severe drain on my time.

**Comment by La0** [comment]
Would you consider a patch from Teklia if we [apply the official migration guide](https://shapely.readthedocs.io/en/stable/migration.html) on your codebase ?

**Comment by mittagessen** [comment]
The migration guide only accounts for API changes and not for behavior changes largely due to different versions of the underlying GEOM library. In fact, I already did the migration almost two years ago (eb89ab6f01ab2f961b6aecadc7552b14808674be) but had to roll it back 6 months later as hunting down all the new corner cases became intractable.
Apparently, now there are some new functions to deal with precision which might or might not resolve a lot of these issues but I haven't tried them yet. The big issue is really the polygon calculation which is rather more complex than most uses of the library.
I'd absolutely love a PR but it is much more work than just mechanically applying the API changes.

**Comment by mittagessen** [comment]
Do you have a test case I can run to see what's going on? The polygon *calculation* is untouched (apart from faster rotation code), only the extraction of line images with baseline/polygons has been improved.

**Comment by mittagessen** [comment]
The new 5.3.0 release bumps shapely up to 2.0.x.
