### ISSUE TITLE
finetune error on altos containing &gt; or &lt; as txt

### ISSUE THREAD

**Issue by dstoekl** [mittagessen/kraken#616]
Finetuning on altos with &gt; or &lt; fails with the following error:
![image](https://github.com/mittagessen/kraken/assets/39535215/e8bb2c09-ed2e-4975-81e7-d4eeb125a64c)
![image](https://github.com/mittagessen/kraken/assets/39535215/f6e1f4c4-b4a7-404a-9d53-7cd0b3123571)

**Comment by dstoekl** [comment]
on training from scratch it advances by one codepoint
![image](https://github.com/mittagessen/kraken/assets/39535215/afc975bb-12d1-46d4-9746-607435533476)

**Comment by mittagessen** [comment]
On 24/06/17 01:43PM, Daniel Stoekl wrote:
> on training from scratch it advances by one codepoint
> ![image](https://github.com/mittagessen/kraken/assets/39535215/afc975bb-12d1-46d4-9746-607435533476)

How are they encoded in the XML ? As normal XML entities?

**Comment by dstoekl** [comment]
<String CONTENT="] עד&gt; טאלע ואחואלנא דכרה כלהא וקדוצל מן קבל יוסף קפיז ["
                    HPOS="165.0"
                    VPOS="1066.0"
                    WIDTH="1360.0"
                    HEIGHT="102.0"></String>

**Comment by mittagessen** [comment]
I can't reproduce it. When I train on other data with &gt; it works as
expected and there's nothing that treats those entities differently, in
particular not the codec. If you give me access to your data I can take
a look.

**Comment by mittagessen** [comment]
Thinking about it is probably caused by Unicode mirroring. > is a
mirroring character. The codec is constructed while the text is still in
logical order but the actual encoding happens on lines already
transformed into display order which maps 0x003E to 0x003C which isn't
in the codec as you don't have any 0x003C (<) in there.

As a hotfix you can add a codec that includes < manually when training
from scratch. I need to think a bit if just creating the codec from
display order lines is going to break anything else.

**Comment by mittagessen** [comment]
You can also disable the mirroring by encapsulating the &gt; in
Left-to-Right markers which does make it compatible with fine-tuning as
well.

**Comment by dstoekl** [comment]
It is unclear to users and will crash in eScr
