### ISSUE TITLE
Error while using clstm models that I trained and test it ! 

### ISSUE THREAD

**Issue by Hadi58** [mittagessen/kraken#67]
Hi !
when I use default clstm models like arabic-beirut-200.clstm model, it's ok and convert successfully:
user@user ~/Desktop/mags $ kraken -i images/tt1.jpg image.txt binarize segment ocr -m arabic-beirut-
200.clstm
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Processing	✓
Writing recognition results for /tmp/tmpq1EMeq	✓
but when I use any clstm models that I trained and tested them I get: 
user@user ~/Desktop/mags $ kraken -i images/tt1.jpg image.txt binarize segment ocr -m persian-keyhan-5000.clstm
Loading RNN default	✓
Binarizing	✓
Segmenting	✓
Traceback (most recent call last):
  File "/usr/local/bin/kraken", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1093, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1031, in _process_result
    **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 167, in process_pipeline
    task(base_image=base_image, input=input, output=output)
  File "/usr/local/lib/python2.7/dist-packages/kraken/kraken.py", line 125, in recognizer
    for pred in it:
  File "/usr/local/lib/python2.7/dist-packages/kraken/rpred.py", line 211, in mm_rpred
    pred = nets[script].predictString(line)
  File "/usr/local/lib/python2.7/dist-packages/kraken/lib/models.py", line 88, in predictString
    line = line.reshape(-1, self.rnn.ninput(), 1)
ValueError: can only specify one unknown dimension

---------------------------------------------------------------------------
I use kraken version 0.9.6 :
user@user ~/Desktop/mags $ kraken --version
kraken, version 0.9.6.dev8
and compile `separate-derivs` branch to train my clstm model.

**Comment by mittagessen** [comment]
Could you make the model file available to me, so I can have a look?

**Comment by Hadi58** [comment]
yes! of course!
I sent it to your email.

**Comment by Hadi58** [comment]
Hi mittagessen!
thanks for your attention!

**Comment by mittagessen** [comment]
Sorry, I can't find it. Could you resent it or put it somewhere else? My mail server drops mail over a certain size so it's certainly possible it was lost somewhere.

**Comment by Hadi58** [comment]
Hi mittagessen!
I sent it to your email again and shared this link too.
https://drive.google.com/open?id=0B4rF4dafhi1gSVlQazcySzRSYXc
thanks!

**Comment by christophered** [comment]
@Hadi58 What settings did you use to train clstm?
How did you create the training data, did you scan pages the transcribe? or did you generate artificially using a font by Ketos?

**Comment by Hadi58** [comment]
I scanned old persian newspapers and transcribed and trained and tested them.

**Comment by Hadi58** [comment]
@mittagessen I sent it to your email again and shared this link too.
https://drive.google.com/open?id=0B4rF4dafhi1gSVlQazcySzRSYXc
thanks!

**Comment by jbaiter** [comment]
I'm getting the same error with the `fraktur.clstm` model, i.e. not self-trained.

**Comment by mittagessen** [comment]
The issue stems from the clstm version. CLSTM uses a net layer type registry and resolves those during deserialization with the ``kind`` and ``name`` field (separate_derivs branch) or ``kind`` field only (master). Crucially, the layer identifiers have changed so master models can't be loaded with separate_derivs and vice versa and trying to do so has always caused an assertion for me. In your cases the input dimensionality is misparsed (weird because those fields haven't changed) as `-1` causing the reshape with multiple unknown dimensions (-1, -1, 1). But the models are unmistakenly serialized using master clstm (missing `name` field).

Because the python bindings have been broken on master for a long time kraken has to use the separate_derivs version. I've been working on porting the backend to pytorch (although I haven't had much time for it lately) which will resolve these issues. It is only missing small parts such as the OpenML serialization so it shouldn't be much longer.
