### ISSUE TITLE
Kraken.re web site issues

### ISSUE THREAD

**Issue by stevewgithub** [mittagessen/kraken#70]
Here are some issues on the kracken.re web site:
My tests are using kraken 0.9.7 in Ubuntu 17.04.  I used "pip install kraken".  I used Windows 10 Firefox and Chrome for the browser part.

Training a kraken model page: http://kraken.re/training.html
 Transctription section.
  There is an error on this line on the web page.  The e on the end of transcribe is missing:
     $ ketos transcrib -o output.html image_1.png image_2.png ... 
  It should read:
     $ ketos transcribe -o output.html image_1.png image_2.png ... 

The Download button on the transcription page is actually in the lower left (not right):

After transcribing a number of lines the results have to be saved, either using the Download button on the lower **right** or through the regular Save Page As function of the browser.
Should read:
After transcribing a number of lines the results have to be saved, either using the Download button on the lower left or through the regular Save Page As function of the browser. 

I was able to use Save Page As or the Download button in Firefox.   I was not able to get Google Chrome to show any of the text I had filled in and saved, or to save.  The Download button in Chrome wasn't working for me.  I could not find a "Save page as in Chrome".  You may wish to recommend Firefox.

--output | The output directory where all line image-text pairs (training data) are written.
   Please add something like: By default it creates the directory training/

--normalization NFD
  This generates "FutureWarning: The behavior of this method will change in future versions..."
  Is there a better normalization method to recommend now?

I don't see train.sh anywhere in the file system.  I see that you have it in the vagrant VM.  It would be good to include it in the pip install, or link to it on the web site.  I still haven't found it.  I'm not going to use the vagrant VM because I have already spent hours on the Docker version.

I also see issues on https://pypi.python.org/pypi/kraken also.  That is where I went first when trying to install.  All of the links are broken there, including to the readme.md.  It looks like this:
<https: github.com="" tmbdev="" clstm="" blob="" master="" readme.md="">`_ to install build
dependencies.

**Comment by mittagessen** [comment]
Thanks, I've fixed the small documentation issues but can't reproduce the Chrome one. It works for me with version 62 and multiple people have been transcribing on it. Its ``Save page as`` is also accessed the same way as in Firefox (right click -> save as or just CTRL+S).

The ``ketos extract`` warning had nothing to do with NFD as a normalization but was caused by soon-to-be obsolete way to check None-ness of a variable (text direction in this case). 

The rendering of the pypi description is also fixed, apparently their renderer doesn't like multiple links with identical names.

``train.sh`` is only in the vagrant box because it runs the ``clstmocrtrain`` binary which can't be installed through python packaging. I don't know about any docker containers; I certainly didn't package them. There are statically linked (clstmocrtrain)[http://br.unchti.me/clstmocrtrain] and (train.sh)[http://br.unchti.me/train.sh], copy the executable to ``/usr/local/bin`` and run the script as described in the documentation. I'm working on integrating the training directly into ketos but am incredibly occupied till mid-February and won't be able to work much on it.
