### ISSUE TITLE
Ketos command fails

### ISSUE THREAD

**Issue by strn** [mittagessen/kraken#73]
Hi,

When running ketos command like this:
`ketos linegen -f Arial -fs 12 -fw 200 -n 1000 -l "sr-Cyrl" /path/to/text.txt`
command fails with error message

>   File "/usr/local/lib/python3.6/site-packages/kraken/linegen.py", line 144, in render_line
    width, height = _draw_on_surface(temp_surface, self.font, self.language, text)
  File "/usr/local/lib/python3.6/site-packages/kraken/linegen.py", line 170, in _draw_on_surface
    pango.pango_context_set_language(pangocairo_ctx, pango_language)
ctypes.ArgumentError: argument 2: <class 'AttributeError'>: 'int' object has no attribute 'encode'

I have installed kraken 0.9.8 with both Python 2 and 3 - result is the same in both cases. What am I doing wrong?

**Comment by mittagessen** [comment]
That's a bug. I don't remember why but I only half-assedly statically typed all the pango/cairo functions. I'll merge the fix on the weekend including a slightly better degradation model if I can find the code again.

You're creating data for one of the few scripts where setting the language is needed for proper display which is why it dropped through the cracks. Sorry for that.

**Comment by strn** [comment]
Thanks for quick reply. I'll check _ketos_ on Monday.
