### ISSUE TITLE
Ketos Training from scratch is not supported yet

### ISSUE THREAD

**Issue by Usamamalik007** [mittagessen/kraken#92]
When will the support come?

**Comment by mittagessen** [comment]
It is there and has been since May on the master branch. The online documentation is for current stable which indeed doesn't support it. To train with ketos you need to install [pytorch-nightly](https://pytorch.org/) and then install kraken from the master branch. It is stable and the only reason I haven't tagged and packaged a new release yet is that I'm waiting for the next pytorch stable release so I can keep the pip installation procedure uncomplicated.

**Comment by mittagessen** [comment]
The documentation on how to use it is in the docs/training.rst file. I didn't manage to get multi-version sphinx working which would've allowed publishing both master and stable docs on the website.
